### ISSUE TITLE
Difference with LIQA

### ISSUE THREAD

**Issue by doshirLV** [WGLab/DELongSeq#2]
Dear WGLab developers,

- The paper mentions that this tool "can be naturally paired with LIQA" but then also states that the "current model of DELongSeq is based on read length correction of LIQA." Initially, it seems like one would use LIQA first and then feed that output into DELongSeq.
- When looking at the documentation in this repo, though, it appears that DELongSeq is just an improved version of LIQA.

So my question is, is this new tool a standalone product to do differential expression analysis or do I use it in coordination with LIQA to generate results from my RNA-seq data? 

Thank you for the clarification,
Raj Doshi

**Comment by huyustats** [comment]
Hi,

Thanks for your interests in using LIQA and DELongSeq. DELongSeq can take isoform expression estimates as input for DE analysis. Moreover, the DE function has been integrated in LIQA as well. You can conduct both isoform expression quantification and DE analysis using LIQA as well. Thanks!

**Comment by doshirLV** [comment]
So in that way, these two tools are identical? Or if I am wrong, please correct me, and help me understand what the difference is between them. Kind Regards.

**Comment by huyustats** [comment]
Sorry for the confusion. No, DELongSeq applies meta regression model for DE detection while LIQA applies beta regression model. However, the meta regression was integrated to LIQA.  Overall, LIQA is a more comprehensive tool. Currently, we are developing and integrating novel isoform detection function to LIQA as well. Thanks.

**Comment by doshirLV** [comment]
Okay, that makes more sense now and I believe LIQA will be best for my usage purposes. 
Just to confirm I am working with the right one, what version number was the meta-regression integrated? Much appreciated.
