### ISSUE TITLE
DELong seq

### ISSUE THREAD

**Issue by dlata123** [WGLab/DELongSeq#3]
Hello I am trying to install DElong seq, is there anything else we need to do apart from downloading, I was unable to get further information from the Readme file about the steps. I have all the Prerequisites in place. Thanks alot for help.
git clone https://github.com/WGLab/DELongSeq.git
cd DELongSeq

**Comment by kaichop** [comment]
you can run " python bin/delongseq.py "  after cd-ing into the directory
